### ISSUE TITLE
Anchor doesn't work as expected.

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-anchor#1]
It's a surprise to see this lib so fast! Thanks for you indeed.

I'm not sure whether it is completed or not, consider this report to be a test report rather than a issue, :P

The anchor doens't work as expected. Here is the code:
```rust
use fltk::{prelude::*, *};
use fltk_anchor::{Anchor, Anchored};

fn main() {
    let a = app::App::default();
    let mut win = window::Window::default().with_size(400, 300);

    const PADDING: i32 = 8;

    button::Button::new(PADDING, PADDING, 80, 40, "Click").with_anchor(Anchor::Left | Anchor::Top);

    input::MultilineInput::new(
        PADDING,
        PADDING * 2 + 40,
        400 - PADDING * 2,
        300 - 40 - PADDING * 3,
        "",
    )
    .with_anchor(Anchor::Left | Anchor::Right | Anchor::Top | Anchor::Bottom);

    win.end();

    win.make_resizable(true);
    win.show();

    a.run().unwrap();
}
```

My expectation is, during the resizing, button would has fixed position and size. And input's position is fixed, it's size would be always "fill" the remain spaces of parent window.

In my understanding, `Anchor::Left` means the distance between widget's left border and parent window's left border is fixed.

So the input widget should be able to `fill` remain spaces of parent window all the time. It's size should be calculated like this:
```
input.width = input.parent().width() - PADDING * 2
input.height = input.parent().height() - button.height() - PADDING * 3
```

Here is the initial layout looks like.
![截屏2021-09-04 下午5 48 37](https://user-images.githubusercontent.com/18550/132090488-ce8117ff-5914-4dec-bafc-9d5692c9de0f.png)

After resize, it looks like this.
![截屏2021-09-04 下午5 48 46](https://user-images.githubusercontent.com/18550/132090510-0db20b6f-b4c8-4fe1-a682-85449e47f403.png)

**Comment by MoAlyousef** [comment]
I have updated the version with what I think is a fix. Can you try it?

**Comment by AllenDang** [comment]
@MoAlyousef No, still has issue.

```rust
use fltk::button::Button;
use fltk::text::TextDisplay;
use fltk::valuator::{Slider, SliderType};
use fltk::window::Window;
use fltk::{prelude::*, *};
use fltk_anchor::{Anchor, Anchored};
use fltk_theme::{color_themes, ColorTheme};

mod mainview;

fn main() {
    let app = app::App::default().with_scheme(app::Scheme::Gtk);

    let theme = ColorTheme::from_colormap(color_themes::BLACK_THEME);
    theme.apply();

    let mut win = Window::new(438, 193, 565, 518, "Fl2Rust test");

    let mut button1 = Button::new(10, 10, 80, 25, "Button");
    let mut button2 = Button::new(475, 10, 80, 25, "Button2");
    let mut button3 = Button::new(475, 483, 80, 25, "Button3");
    let mut button4 = Button::new(10, 483, 80, 25, "Button4");

    let mut slider = Slider::new(10, 45, 545, 30, "Slider");
    slider.set_type(SliderType::Horizontal);

    let mut text_display = TextDisplay::new(10, 105, 545, 372, None);

    button1.set_anchor(Anchor::Left | Anchor::Top);
    button2.set_anchor(Anchor::Right | Anchor::Top);
    button3.set_anchor(Anchor::Right | Anchor::Bottom);
    button4.set_anchor(Anchor::Left | Anchor::Bottom);

    slider.set_anchor(Anchor::Left | Anchor::Top | Anchor::Right);

    text_display.set_anchor(Anchor::Left | Anchor::Top | Anchor::Right | Anchor::Bottom);

    win.end();
    win.make_resizable(true);
    win.show();

    app.run().unwrap();
}
```

Here is the initial state
![截屏2021-09-05 下午1 56 08](https://user-images.githubusercontent.com/18550/132117088-61db1c7a-1b7f-4049-9a67-7e1086168408.png)

After resize, it turns to
![截屏2021-09-05 下午1 56 27](https://user-images.githubusercontent.com/18550/132117094-b7261225-f319-43a1-82b0-e3646b0553bb.png)

**Comment by MoAlyousef** [comment]
I've uploaded a fix. I'll try out all combinations to see if things work out before I publish a new version.

**Comment by AllenDang** [comment]
@MoAlyousef Example2 is fixed. :P
I will do more test with various containers. Feedback to you later.
BTW, is it possible to add anchor setting to fltk-fliud?

**Comment by AllenDang** [comment]
@MoAlyousef It doesn't work well with tile.

![commatolines](https://user-images.githubusercontent.com/18550/132129843-938513fa-1b0c-4ac9-991c-a8ebb8cab9cc.gif)

```rust
use fltk::button::Button;
use fltk::enums::FrameType;
use fltk::group::{Group, Tile};
use fltk::window::Window;
use fltk::{prelude::*, *};
use fltk_anchor::{Anchor, Anchored};
use fltk_theme::{color_themes, ColorTheme};

mod mainview;

fn main() {
    let app = app::App::default().with_scheme(app::Scheme::Gtk);

    let theme = ColorTheme::from_colormap(color_themes::BLACK_THEME);
    theme.apply();

    let mut win = Window::new(485, 196, 500, 400, None);

    let tile = Tile::new(0, -5, 500, 405, None);

    let mut group_left = Group::new(0, 0, 100, 400, None);
    group_left.set_frame(FrameType::DownBox);

    group_left.end();

    let mut group_right = Group::new(100, 0, 400, 400, None);

    let mut button1 = Button::new(110, 10, 65, 25, "Button1");
    let mut button2 = Button::new(417, 45, 73, 25, "Button2");
    let mut button3 = Button::new(110, 80, 380, 25, "Button3");
    let mut button4 = Button::new(420, 365, 70, 25, "Button4");

    button1.set_anchor(Anchor::Left | Anchor::Top);
    button2.set_anchor(Anchor::Right | Anchor::Top);
    button3.set_anchor(Anchor::Left | Anchor::Right | Anchor::Top);
    button4.set_anchor(Anchor::Right | Anchor::Bottom);

    group_right.set_frame(FrameType::DownBox);
    group_right.end();

    tile.end();

    win.end();

    win.make_resizable(true);

    win.show();

    app.run().unwrap();
}

```

**Comment by MoAlyousef** [comment]
I don't think it's possible to apply this to Tiles or Packs, basically any container that does its own layout, since these are applied at the end of a resize.
Also since fluid is just wrapping the C++ fluid code base, adding anchors to it would require non-trivial modification to the original. I would wait to see what FLTK offers in terms of layout, and that will be added automatically to fluid.

**Comment by AllenDang** [comment]
@MoAlyousef Understood. Thanks for your work!
